
# Site settings
title: Data4Development
email: rolf@data4development.nl
description: Home of the Data4Development developer pages
brand: Data4Development
brand_url: /
github: https://github.com/data4development/data4development.github.io

defaults:
  -
    values:
      layout: "default"

remote_theme: data4development/dataworkbench-jekyll-theme
